name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-caching:
    name: Test caching
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: bear
          version: 1.0

      - name: Set up clang-tidy-cache
        uses: ./
        with:
          key: test-cache-loading

      - name: Set up test files
        run: |
          clang-tidy-cache --show-stats
          echo "int x = $RANDOM;" > test.cpp
          bear -- clang++ -c test.cpp
          clang-tidy-cache --clean
          clang-tidy-cache --show-stats | grep "Hit count.* 0"

      - name: Run the linter
        run: |
          clang-tidy-cache clang-tidy test.cpp

      - name: Test
        run: |
          clang-tidy-cache --show-stats | grep "Hit count.* 0"

      - name: Run the linter again
        run: |
          clang-tidy-cache clang-tidy test.cpp

      - name: Test again
        run: |
          clang-tidy-cache --show-stats | grep "Hit count.* 1"


  test-cache-loading:
    name: Test caching
    runs-on: ubuntu-22.04
    needs: [test-caching]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: bear
          version: 1.0

      - name: Set up clang-tidy-cache
        uses: ./
        with:
          key: test-cache-loading

      - name: Test
        run: |
          clang-tidy-cache --show-stats | grep "Hit count.* 1"

      - name: Run the linter again
        run: |
          clang-tidy-cache clang-tidy test.cpp

      - name: Test again
        run: |
          clang-tidy-cache --show-stats | grep "Hit count.* 2"
